medqa_examples = [
    {
        "question":"A 54-year-old man with hypertension and congenital blindness comes to the physician because he is unable to recognize objects by touch with his right hand. The symptoms started about 2 hours ago. When given a house key, he can feel the object in his right hand but is not able to identify what it is. This patient's condition is most likely caused by a lesion in which of the following locations?",
        "thought":"""This patient presents with astereognosis (the inability to recognize objects by touch despite intact sensation), which suggests damage to the somatosensory association cortex in the contralateral parietal lobe (specifically, the superior parietal lobule). Since his right hand is affected, the lesion is most likely in the left parietal cortex (specifically, the left superior parietal lobule of the postcentral gyrus, Brodmann areas 5 and 7).\nThe primary somatosensory cortex (postcentral gyrus) receives tactile sensory input, but the somatosensory association cortex is responsible for interpreting this sensory information, allowing for object recognition by touch. A lesion here results in tactile agnosia, which is the inability to recognize objects by touch alone. \nGiven the acute onset, this is likely due to an ischemic stroke in the left middle cerebral artery (MCA) territory, affecting the parietal lobe."""
    },
    {
        "question":"A 35-year-old man and his 9-year-old son are brought to the emergency department following a high-speed motor vehicle collision. The father was the restrained driver. He is conscious. His pulse is 135/min and blood pressure is 76/55 mm Hg. His hemoglobin concentration is 5.9 g/dL. His son sustained multiple body contusions and loss of consciousness. He remains unresponsive in the emergency department. A focused assessment of the boy with sonography is concerning for multiple organ lacerations and internal bleeding. The physician decides to move the man's son to the operating room for emergency surgical exploration. The father says that he and his son are Jehovah's witnesses and do not want blood transfusions. The physician calls the boy's biological mother who confirms this religious belief. She also asks the physician to wait for her arrival before any other medical decisions are undertaken. Which of the following is the most appropriate next step for the physician?",
        "thought":"""In life-threatening emergencies, a child's best interest overrides parental objections. Since delaying treatment could result in death, the physician should proceed with surgery and administer a blood transfusion if necessary."""
    },
    {
        "question":"A 38-year-old man presents to the emergency department with chest pain and difficulty breathing for the last 3 hours. He denies cough, nasal discharge or congestion, sneezing, and palpitations. There is no history of recent surgery or hospitalization but he mentions that he was diagnosed with a psychiatric disorder 6 months ago and has been on medication, as prescribed by the psychiatrist. His past medical history is negative for any cardiac or respiratory conditions. His temperature is 38.1°C (100.5°F), pulse is 112/min, blood pressure is 128/84 mm Hg, and respiratory rate is 24/min. Auscultation of the chest reveals crackles and a decreased intensity of breath sounds over the right infrascapular region. The heart sounds are normal and there are no murmurs. His plasma D-dimer level is elevated. A contrast-enhanced computed tomography (CT) of the chest shows a filling defect in 2 segmental pulmonary arteries on the right side. Which of the following medications is most likely to cause the condition found in this man?",
        "thought":"""The most likely medication causing this patient’s condition is an antipsychotic, such as risperidone or olanzapine. This patient presents with acute pulmonary embolism (PE), as evidenced by his chest pain, tachycardia, elevated D-dimer, and CT findings of a pulmonary arterial filling defect. The use of antipsychotic medications is a well-known risk factor for venous thromboembolism (VTE), including PE, due to their pro-thrombotic effects, such as increased platelet aggregation and sedation-related immobility. This risk is particularly high in second-generation (atypical) antipsychotics like clozapine, olanzapine, and risperidone."""
    },
    {
        "question":"A 47-year-old Caucasian woman presents with a 2-month history of general fatigue, slight jaundice, and mild itching. She has also noticed that her urine has been darker and stools have been lighter in color recently. She denies any fevers, chills, or alcohol use. She has no significant past medical or surgical history and is not taking any medications. She recalls that her mother saw a doctor for eye and mouth dryness but cannot remember the name of her diagnosis. She denies any illicit drug use, recent change in diet, or recent travel. On physical exam, her abdomen is soft and non-distended. There is right upper quadrant tenderness to deep palpation but a negative Murphy’s sign. Her laboratory findings were significant for increased liver enzymes, direct bilirubin, and alkaline phosphatase with normal levels of iron and ceruloplasmin. Ultrasound revealed no stones in the gallbladder or common bile duct and endoscopic retrograde cholangiopancreatography (ERCP) revealed normal extrahepatic biliary ducts. Which of the following findings is most likely to also be found in this patient?",
        "thought":"""This patient likely has primary biliary cholangitis (PBC), an autoimmune disease causing intrahepatic bile duct destruction. A key finding is positive antimitochondrial antibodies (AMAs). Her symptoms of jaundice, pruritus, and cholestatic liver enzyme elevation, along with a family history of autoimmune disease, strongly support this diagnosis."""
    },
    {
        "question":"A 33-year-old woman presents to the clinic complaining of a 9-month history of weight loss, fatigue, and a general sense of malaise. She additionally complains of an unusual sensation in her chest upon rapidly rising from a supine to a standing position. Current vitals include a temperature of 36.8°C (98.2°F), pulse of 72/min, blood pressure of 118/63 mm Hg, and a respiratory rate of 15/min. Her BMI is 21 kg/m2. Auscultation demonstrates an early-mid diastole low-pitched sound at the apex of the heart. A chest X-ray reveals a poorly demarcated abnormality in the heart and requires CT imaging for further analysis. What would most likely be seen on CT imaging?",
        "thought":"""This patient likely has a left atrial myxoma, the most common primary cardiac tumor. CT imaging would reveal a well-demarcated, pedunculated mass in the left atrium, often attached to the interatrial septum. The diastolic sound heard on auscultation suggests tumor plop, caused by obstruction of blood flow through the mitral valve."""
    },
    {
        "question":"A 26-year-old G1P0 female who is 39 weeks pregnant presents to the emergency department in labor. She reports following her primary care physician’s recommendations throughout her pregnancy and has not had any complications. During delivery, the baby’s head turtled back into the vaginal canal and did not advance any further. The neonatal intensivist was called for shoulder dystocia and a baby girl was able to be delivered vaginally 6 minutes later. Upon initial assessment, the baby appeared pale throughout, had her arms and legs flexed without active motion, and had some flexion of extremities when stimulated. Her pulse is 120/min and had irregular respirations. What is this baby’s initial APGAR score?",
        "thought":"""The baby's initial APGAR score is 5, indicating moderate perinatal distress. She receives 0 points for appearance due to generalized pallor, 2 points for pulse as her heart rate is 120/min, 1 point for grimace since she shows some flexion when stimulated, 1 point for activity due to flexed extremities without active motion, and 0 points for respiration due to irregular breathing. Given the history of shoulder dystocia and delayed delivery, she requires close monitoring and possible respiratory support."""
    },
    {
        "question":"An investigator is studying vitamin D metabolism in mice. He induces a gene mutation that interferes with the function of an enzyme in the renal proximal tubules that is required for vitamin D activation. He then measures serum levels of various metabolites. Production of which of the following will be impaired in this mouse?",
        "thought":"""The mutation affects the enzyme 1α-hydroxylase in the renal proximal tubules, which is responsible for converting 25-hydroxyvitamin D (25-OH D) into its active form, 1,25-dihydroxyvitamin D (1,25-(OH)₂ D). As a result, the production of 1,25-dihydroxyvitamin D will be impaired, leading to decreased calcium absorption and potential bone metabolism issues.""" 
    },
    {
        "question":"A 35-year-old G1 is brought to the emergency department because of sharp pains in her abdomen. She is at 30 weeks gestation based on ultrasound. She complains of  feeling a little uneasy during the last 3 weeks of her pregnancy. She mentions that her abdomen has not been enlarging as expected and her baby is not moving as much as during the earlier part of the pregnancy. If anything, she noticed her abdomen has decreased in size. While she is giving her history, the emergency medicine physician notices that she is restless and is sweating profusely. An ultrasound is performed and her blood is sent for type and match. The blood pressure is 90/60 mm Hg, the pulse is 120/min, and the respiratory rate  is 18/min. The fetal ultrasound is significant for no fetal heart motion or fetal movement. Her blood work shows the following: hemoglobin, 10.3 g/dL; platelet count, 1.1*10(5)/ml; bleeding time, 10 minutes; PT, 25 seconds; and PTT, 45 seconds. Which of the following would be the best immediate course of management for this patient?",
        "thought":"""This patient has placental abruption with intrauterine fetal demise (IUFD) complicated by DIC, as indicated by fetal death, coagulopathy, and hemodynamic instability. The best immediate management is urgent delivery to prevent further maternal complications, along with fluid resuscitation and blood product transfusion as needed."""
    },
]